server:
  port: 8088
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config, classpath:/common
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8085/eureka/