server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:3311/cartservice_db
    username: pxl
    password: pxl
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
