server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - RewritePath=/cart/(?<path>.*), /$\{path}
        - id: logbook-service
          uri: lb://logbook-service
          predicates:
            - Path=/logbook/**
          filters:
            - RewritePath=/logbook/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
